#!/usr/bin/env python3
"""
WFLOP IMPLEMENTATION FACT DECLARATION
Implementation unit: T14 immutable wind-resource and Amalia-boundary generator
Paper/DOI: Massive Simplification of the Wind Farm Layout Optimization
Problem; 10.5194/wes-4-663-2019
Public source: https://github.com/byuflowlab/stanley2019-variable-reduction
at revision 62b590065f9541c4296338b3f1a0ee07cfcd28bc; archival DOI
10.5281/zenodo.3523383
Provided assets: three wind-rose functions, Princess Amalia coordinates, and
the Python 2/OpenMDAO plus Fortran experiment implementation
Missing/conflicts: the archive has no root LICENSE file; setupRevision.py
declares Apache License 2.0; the wind-rose module depends on an unbundled
legacy `akima` package and its direction-zero integration repeats the positive
half-bin instead of wrapping the negative half-bin
Reconstruction and resolution: execute only the public wind-resource
functions with a compatibility Akima wrapper backed by SciPy and preserve the
published direction-zero behavior; emit fixed 24-bin and 360-bin resource
tables plus the public Amalia points so production code has no Python/runtime
dependency
Method/problem semantic IDs: t14_boundary_grid_parameterization_v1;
t14_stanley_2019_seven_unique_cases_v1
Controlling contract: shared/contracts/core99_t14_stanley_2019.json
Claim boundary: generated factual inputs for an academic declared
reproduction, not author-runtime replay
Last evidence-audit date: 2026-07-31
END WFLOP IMPLEMENTATION FACT DECLARATION
"""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

import numpy as np
from scipy.interpolate import Akima1DInterpolator

if not hasattr(np, "trapz"):
    np.trapz = np.trapezoid


class Akima:
    """Compatibility surface for the unbundled legacy `akima.Akima` class."""

    def __init__(self, x: np.ndarray, y: np.ndarray):
        self._interpolator = Akima1DInterpolator(x, y, extrapolate=True)

    def interp(self, value: float) -> tuple[float, float, float, float]:
        return (float(self._interpolator(value)), 0.0, 0.0, 0.0)


def load_public_module(path: Path) -> dict[str, object]:
    text = path.read_text(encoding="utf-8")
    text = text.replace("from akima import Akima, akima_interp", "")
    text = text.replace("num_int/2", "num_int//2")
    text = re.sub(
        r"^(\s*)print\s+([^\n]+)$",
        r"\1# Python-2 diagnostic omitted: print \2",
        text,
        flags=re.MULTILINE,
    )
    namespace: dict[str, object] = {
        "__name__": "_core99_t14_wind_roses",
        "Akima": Akima,
    }
    exec(compile(text, str(path), "exec"), namespace)
    return namespace


def array(name: str, values: np.ndarray) -> str:
    encoded = ",\n        ".join(f"{float(value):.17g}" for value in values)
    return (
        f"inline constexpr std::array<double, {values.size}> {name} = {{\n"
        f"        {encoded}\n"
        "};\n"
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source-root", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--oracle-data-output", type=Path)
    arguments = parser.parse_args()
    module = load_public_module(arguments.source_root / "windRoses.py")
    parts = [
        "/*\n",
        "WFLOP IMPLEMENTATION FACT DECLARATION\n",
        "Implementation unit: generated T14 wind-resource and Amalia arrays\n",
        "Paper/DOI: Massive Simplification of the Wind Farm Layout Optimization Problem; 10.5194/wes-4-663-2019\n",
        "Public source: https://github.com/byuflowlab/stanley2019-variable-reduction revision 62b590065f9541c4296338b3f1a0ee07cfcd28bc\n",
        "Provided/missing/conflicts and reconstruction: scripts/generate_core99_t14_data.py\n",
        "Method/problem semantic IDs: t14_boundary_grid_parameterization_v1; t14_stanley_2019_seven_unique_cases_v1\n",
        "Controlling contract: shared/contracts/core99_t14_stanley_2019.json\n",
        "Claim boundary: generated public factual inputs, not author-runtime replay\n",
        "Last evidence-audit date: 2026-07-31\n",
        "END WFLOP IMPLEMENTATION FACT DECLARATION\n",
        "*/\n",
        "/* Generated by scripts/generate_core99_t14_data.py. */\n",
        "#pragma once\n\n",
        "#include <array>\n\n",
        "namespace core99::t14::data {\n\n",
    ]
    functions = {
        "north_island": module["northIslandRose"],
        "ukiah": module["ukiahRose"],
        "victorville": module["victorvilleRose"],
    }
    oracle_data: dict[str, dict[str, list[float]]] = {}
    for identifier, function in functions.items():
        oracle_data[identifier] = {}
        for bins in (24, 360):
            directions, frequencies, speeds = function(bins, nSpeeds=1)
            oracle_data[identifier][f"directions_{bins}"] = [
                float(value) for value in directions
            ]
            oracle_data[identifier][f"frequencies_{bins}"] = [
                float(value) for value in frequencies
            ]
            oracle_data[identifier][f"mean_speeds_{bins}"] = [
                float(value) for value in speeds
            ]
            parts.append(array(
                f"k{identifier.title().replace('_', '')}Directions{bins}",
                np.asarray(directions),
            ))
            parts.append(array(
                f"k{identifier.title().replace('_', '')}Frequencies{bins}",
                np.asarray(frequencies),
            ))
            parts.append(array(
                f"k{identifier.title().replace('_', '')}MeanSpeeds{bins}",
                np.asarray(speeds),
            ))
            parts.append("\n")
    amalia = np.loadtxt(
        arguments.source_root / "layout_amalia.txt",
        comments="#",
    ).reshape(-1)
    parts.append(array("kAmaliaCoordinates", amalia))
    parts.append("\n}  // namespace core99::t14::data\n")
    arguments.output.parent.mkdir(parents=True, exist_ok=True)
    arguments.output.write_text("".join(parts), encoding="utf-8")
    if arguments.oracle_data_output is not None:
        arguments.oracle_data_output.parent.mkdir(parents=True, exist_ok=True)
        arguments.oracle_data_output.write_text(
            json.dumps(
                {
                    "generator": "scripts/generate_core99_t14_data.py",
                    "paper_doi": "10.5194/wes-4-663-2019",
                    "public_source_revision":
                        "62b590065f9541c4296338b3f1a0ee07cfcd28bc",
                    "resources": oracle_data,
                },
                indent=2,
                sort_keys=True,
            ) + "\n",
            encoding="utf-8",
        )


if __name__ == "__main__":
    main()
